# for this production build:
# hostname, username, database, password, connection string
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3
  

production:
  adapter: postgresql
  database: railway
  username: postgres
  password: QMuIrRGG8yWgUvt42E1o
  host: containers-us-west-52.railway.app
  port: 6736
  pool: 5
  # postgres://USER:PASSWORD@INTERNAL_HOST:PORT/DATABASE
  # some frameworks shall allow the use of a conection string to access the database
