# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

default: &default
  adapter: postgresql
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3

# for this production build:
# hostname, username, database, password, connection string
production:
  <<: *default
  database: bike_fleet_app
  username: bike_fleet_app
  hostname: dpg-cfuuq753t39doauui3e0-a
  url: <%= ENV['DATABASE_URL'] %>
  password: <%= ENV['BIKE_FLEET_DATABASE_PASSWORD'] %>
  # postgres://USER:PASSWORD@INTERNAL_HOST:PORT/DATABASE
  # some frameworks shall allow the use of a conection string to access the database
